steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['clean', 'stage']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/crawler', '.']
images: ['gcr.io/$PROJECT_ID/crawler']
